// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDctFI7mj8H50wQ2inV2GzxHPkcTfSIEPo',
    appId: '1:979138882481:web:fcd0a91df359b25a54eb90',
    messagingSenderId: '979138882481',
    projectId: 'langarden',
    authDomain: 'langarden.firebaseapp.com',
    storageBucket: 'langarden.firebasestorage.app',
    measurementId: 'G-NCEGS14RS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyzlKooyLV20wDCZT6ocmJarjTONAObQ',
    appId: '1:979138882481:android:d5e5d3191fc7426b54eb90',
    messagingSenderId: '979138882481',
    projectId: 'langarden',
    storageBucket: 'langarden.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5R9UGP_SRgk__3r-lzbRvfvg9ZK4j6rE',
    appId: '1:979138882481:ios:515b26828271e9a354eb90',
    messagingSenderId: '979138882481',
    projectId: 'langarden',
    storageBucket: 'langarden.firebasestorage.app',
    androidClientId: '979138882481-f6kqojro3gk8vk6bjoc2sg591ou7rpnk.apps.googleusercontent.com',
    iosClientId: '979138882481-iiul5hc26g72eqh6le0qefju4f382etp.apps.googleusercontent.com',
    iosBundleId: 'com.example.langbat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5R9UGP_SRgk__3r-lzbRvfvg9ZK4j6rE',
    appId: '1:979138882481:ios:515b26828271e9a354eb90',
    messagingSenderId: '979138882481',
    projectId: 'langarden',
    storageBucket: 'langarden.firebasestorage.app',
    androidClientId: '979138882481-f6kqojro3gk8vk6bjoc2sg591ou7rpnk.apps.googleusercontent.com',
    iosClientId: '979138882481-iiul5hc26g72eqh6le0qefju4f382etp.apps.googleusercontent.com',
    iosBundleId: 'com.example.langbat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDctFI7mj8H50wQ2inV2GzxHPkcTfSIEPo',
    appId: '1:979138882481:web:c46c08a3e4cf691f54eb90',
    messagingSenderId: '979138882481',
    projectId: 'langarden',
    authDomain: 'langarden.firebaseapp.com',
    storageBucket: 'langarden.firebasestorage.app',
    measurementId: 'G-RWENSNLVKE',
  );
}
